code --install-extension aaron-bond.better-comments
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension angular.ng-template
code --install-extension catppuccin.catppuccin-vsc
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension docsmsft.docs-article-templates
code --install-extension docsmsft.docs-authoring-pack
code --install-extension docsmsft.docs-build
code --install-extension docsmsft.docs-images
code --install-extension docsmsft.docs-linting
code --install-extension docsmsft.docs-metadata
code --install-extension docsmsft.docs-preview
code --install-extension docsmsft.docs-scaffolding
code --install-extension docsmsft.docs-yaml
code --install-extension donjayamanne.githistory
code --install-extension dotjoshjohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension editorconfig.editorconfig
code --install-extension eliverlara.andromeda
code --install-extension enkia.tokyo-night
code --install-extension equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.vscode-mysql
code --install-extension github.codespaces
code --install-extension github.remotehub
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension james-yu.latex-workshop
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension learningengineeringoperations.learn-training-ai-assistant
code --install-extension mathworks.language-matlab
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.vscode-github-issue-notebooks
code --install-extension msrvida.vscode-sanddance
code --install-extension oderwat.indent-rainbow
code --install-extension paulosilva.vsc-octave-debugger
code --install-extension pkief.material-icon-theme
code --install-extension pkief.material-product-icons
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension sdras.night-owl
code --install-extension slaier.matlab-complete
code --install-extension toasty-technologies.octave
code --install-extension tonybaloney.vscode-pets
code --install-extension twxs.cmake
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xabikos.javascriptsnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension zignd.html-css-class-completion