code-server --install-extension aaron-bond.better-comments
code-server --install-extension amazonwebservices.aws-toolkit-vscode
code-server --install-extension angular.ng-template
code-server --install-extension catppuccin.catppuccin-vsc
code-server --install-extension catppuccin.catppuccin-vsc-icons
code-server --install-extension christian-kohler.npm-intellisense
code-server --install-extension christian-kohler.path-intellisense
code-server --install-extension davidanson.vscode-markdownlint
code-server --install-extension dbaeumer.vscode-eslint
code-server --install-extension docsmsft.docs-article-templates
code-server --install-extension docsmsft.docs-authoring-pack
code-server --install-extension docsmsft.docs-build
code-server --install-extension docsmsft.docs-images
code-server --install-extension docsmsft.docs-linting
code-server --install-extension docsmsft.docs-metadata
code-server --install-extension docsmsft.docs-preview
code-server --install-extension docsmsft.docs-scaffolding
code-server --install-extension docsmsft.docs-yaml
code-server --install-extension donjayamanne.githistory
code-server --install-extension dotjoshjohnson.xml
code-server --install-extension dracula-theme.theme-dracula
code-server --install-extension dsznajder.es7-react-js-snippets
code-server --install-extension eamodio.gitlens
code-server --install-extension ecmel.vscode-html-css
code-server --install-extension editorconfig.editorconfig
code-server --install-extension eliverlara.andromeda
code-server --install-extension enkia.tokyo-night
code-server --install-extension equinusocio.vsc-material-theme
code-server --install-extension equinusocio.vsc-material-theme-icons
code-server --install-extension esbenp.prettier-vscode
code-server --install-extension felipecaputo.git-project-manager
code-server --install-extension formulahendry.auto-close-tag
code-server --install-extension formulahendry.auto-rename-tag
code-server --install-extension formulahendry.vscode-mysql
code-server --install-extension github.codespaces
code-server --install-extension github.remotehub
code-server --install-extension github.vscode-github-actions
code-server --install-extension github.vscode-pull-request-github
code-server --install-extension james-yu.latex-workshop
code-server --install-extension jeff-hykin.better-cpp-syntax
code-server --install-extension learningengineeringoperations.learn-training-ai-assistant
code-server --install-extension mathworks.language-matlab
code-server --install-extension mhutchie.git-graph
code-server --install-extension miguelsolorio.fluent-icons
code-server --install-extension ms-ceintl.vscode-language-pack-ja
code-server --install-extension ms-dotnettools.csharp
code-server --install-extension ms-dotnettools.dotnet-interactive-vscode
code-server --install-extension ms-dotnettools.vscode-dotnet-runtime
code-server --install-extension ms-edgedevtools.vscode-edge-devtools
code-server --install-extension ms-python.debugpy
code-server --install-extension ms-python.isort
code-server --install-extension ms-python.python
code-server --install-extension ms-python.vscode-pylance
code-server --install-extension ms-toolsai.jupyter
code-server --install-extension ms-toolsai.jupyter-keymap
code-server --install-extension ms-toolsai.jupyter-renderers
code-server --install-extension ms-toolsai.vscode-jupyter-cell-tags
code-server --install-extension ms-toolsai.vscode-jupyter-slideshow
code-server --install-extension ms-vscode-remote.remote-containers
code-server --install-extension ms-vscode-remote.remote-ssh
code-server --install-extension ms-vscode-remote.remote-ssh-edit
code-server --install-extension ms-vscode.azure-repos
code-server --install-extension ms-vscode.cmake-tools
code-server --install-extension ms-vscode.cpptools
code-server --install-extension ms-vscode.hexeditor
code-server --install-extension ms-vscode.powershell
code-server --install-extension ms-vscode.remote-explorer
code-server --install-extension ms-vscode.remote-repositories
code-server --install-extension ms-vscode.vscode-github-issue-notebooks
code-server --install-extension msrvida.vscode-sanddance
code-server --install-extension oderwat.indent-rainbow
code-server --install-extension paulosilva.vsc-octave-debugger
code-server --install-extension pkief.material-icon-theme
code-server --install-extension pkief.material-product-icons
code-server --install-extension redhat.java
code-server --install-extension redhat.vscode-xml
code-server --install-extension redhat.vscode-yaml
code-server --install-extension ritwickdey.liveserver
code-server --install-extension sdras.night-owl
code-server --install-extension slaier.matlab-complete
code-server --install-extension toasty-technologies.octave
code-server --install-extension tonybaloney.vscode-pets
code-server --install-extension twxs.cmake
code-server --install-extension visualstudioexptteam.intellicode-api-usage-examples
code-server --install-extension visualstudioexptteam.vscodeintellicode
code-server --install-extension vscjava.vscode-java-debug
code-server --install-extension vscjava.vscode-java-dependency
code-server --install-extension vscjava.vscode-java-pack
code-server --install-extension vscjava.vscode-java-test
code-server --install-extension vscjava.vscode-maven
code-server --install-extension vscode-icons-team.vscode-icons
code-server --install-extension xabikos.javascriptsnippets
code-server --install-extension yzhang.markdown-all-in-one
code-server --install-extension zignd.html-css-class-completion